language: android
jdk: oraclejdk8


before_script:
  - ./travis_before_script.sh

script:
  - ./travis_script.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/


android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # The SDK version used to compile your project
    - android-22
    - android-25

    # The emulator(s) used during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

env:
  matrix:
    - COMPONENT=build
    - COMPONENT=coverage
    - COMPONENT=quality
    - COMPONENT=unittest

git:
  depth: 3 # Clone the last 3 commits
  lfs_skip_smudge: true # Skip LFS (Large File Storage) objects

notifications:
  email:
    on_success: never
    on_failure: change
